import datetime,hashlib,json,subprocess,urllib.request
from pathlib import Path
repo=Path('/home/sky/work/touzi/OneAxe/OpenAgentX-workflow-worktree/docs/reports/validation/2026-10-02-codex-workflow/evidence/installed-provenance01');raw=Path('/home/sky/.local/state/openagentx/evidence/2026-10-02-codex-workflow/installed-provenance01');release=Path('/home/sky/.local/state/openagentx/validation/2026-10-02-codex-workflow/release-clone');installed=Path('/home/sky/.openagentx/web')
def sha(data):return hashlib.sha256(data).hexdigest()
def write(name,obj):
 for d in [raw,repo]:
  p=d/name;p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n' if not isinstance(obj,str) else obj);p.chmod(0o600 if d==raw else 0o644)
def command(argv):
 p=subprocess.run(argv,stdout=subprocess.PIPE,stderr=subprocess.STDOUT,text=True);return {'argv':argv,'exit_code':p.returncode,'output':p.stdout}
before=json.loads((repo/'before-snapshot.json').read_text());after=json.loads((repo/'after-snapshot.json').read_text());api=json.loads((repo/'after-observe.json').read_text());before_api=json.loads((repo/'before-observe.json').read_text())
cmds={'oax_build':command(['go','version','-m','/home/sky/.local/bin/openagentx']),'oax_help':command(['/home/sky/.local/bin/openagentx','--help']),'oax_join_help':command(['/home/sky/.local/bin/openagentx','agent','join','--help']),'codex_version':command([after['processes']['appserver']['exe'],'--version']),'codex_appserver_help':command([after['processes']['appserver']['exe'],'app-server','--help']),'release_tree':command(['git','-C',str(release),'status','--porcelain'])};write('versions-and-help.json',cmds)
opener=urllib.request.build_opener(urllib.request.ProxyHandler({})); assets=[]
for p in sorted((release/'web/dist').rglob('*')):
 if not p.is_file():continue
 rel=p.relative_to(release/'web/dist');i=installed/rel;url='http://127.0.0.1:18100/'+str(rel)
 with opener.open(urllib.request.Request(url,headers={'Cache-Control':'no-cache'}),timeout=15) as r:body=r.read();status=r.status;mime=r.headers.get('Content-Type')
 a={'path':str(rel),'release_sha256':sha(p.read_bytes()),'installed_sha256':sha(i.read_bytes()),'served_sha256':sha(body),'served_status':status,'content_type':mime,'bytes':len(body)};a['all_match']=a['release_sha256']==a['installed_sha256']==a['served_sha256'];assets.append(a)
write('web-assets.json',{'captured_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'release_dist':str(release/'web/dist'),'installed_web':str(installed),'origin':'http://127.0.0.1:18100','request_policy':'direct loopback HTTP, proxy disabled, no-cache','assets':assets,'all_match':all(a['all_match'] for a in assets)})
marker=Path('/home/sky/.openagentx/release.txt').read_text();write('release-marker.txt',marker)
checks={'before_after_targeted_environment_identical':all(before['processes'][k]['environment']==after['processes'][k]['environment'] for k in ['codex_worker','appserver']),'private_environment_file_hash_unchanged':before['environment_file']['sha256']==after['environment_file']['sha256'],'worker_restarted':before['processes']['codex_worker']['pid']!=after['processes']['codex_worker']['pid'] and before['processes']['codex_worker']['starttime_ticks']!=after['processes']['codex_worker']['starttime_ticks'],'appserver_restarted':before['processes']['appserver']['pid']!=after['processes']['appserver']['pid'] and before['processes']['appserver']['starttime_ticks']!=after['processes']['appserver']['starttime_ticks'],'daemon_and_agy_not_restarted_during_capture':all(before['processes'][k]['pid']==after['processes'][k]['pid'] and before['processes'][k]['starttime_ticks']==after['processes'][k]['starttime_ticks'] for k in ['daemon','agy_worker']),'network_generation_advanced':before_api['binding']['applied_generation']==1 and api['binding']['applied_generation']==2,'after_binding_matches_observed_worker':api['binding']['applied_worker_id']==api['worker']['worker_instance_id'] and api['binding']['applied_generation']==api['worker']['generation'],'agent_ready_after_restart':api['agent']['readiness']['ready'],'all_proc_sha_after_match_release':after['checks']['all_oax_proc_sha_match_release'],'codex_version_0_160_0':'0.160.0' in cmds['codex_version']['output'],'go_build_commit_matches_release':'vcs.revision=6b68eeb810c2b65d629cd8a817bad25a21483d5c' in cmds['oax_build']['output'],'go_build_not_modified':'vcs.modified=false' in cmds['oax_build']['output'],'all_help_exit_zero':all(v['exit_code']==0 for v in cmds.values()),'eight_web_assets_match_release_installed_served':len(assets)==8 and all(a['all_match'] for a in assets),'release_marker_matches_commit':'6b68eeb810c2b65d629cd8a817bad25a21483d5c' in marker}
report={'status':'PASS' if all(checks.values()) else 'FAIL','checks':checks,'before_captured_at':before['captured_at'],'after_captured_at':after['captured_at'],'finished_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'evidence_scope':'I installed artifact, actual process identity, served static assets and environment persistence only','fixture_note':'The BEFORE network_applied_current_generation flag only checked binding desired_status due to an absent agent generation field. Do not use that flag as independent worker-generation proof. BEFORE binding records generation 1; corrected AFTER capture explicitly includes WorkerReadModel and compares worker ID/generation 2. Both capture script versions are preserved.','limitations':['No task was dispatched and no services were changed by this verifier.','Root performed the Codex Worker restart between snapshots.','No model call, external network traversal or observed NO_PROXY bypass claim.','No product browser interaction, canceled-tool or business-effect validation in this evidence batch.','E2E can replace appserver later; these checks identify the captured process and time.']};write('report.json',report)
write('README.md','''# 正式安装来源与网络重启持久性独立核验\n\n安装来源：`6b68eeb810c2b65d629cd8a817bad25a21483d5c`；二进制 SHA-256 `f9b74b7df378ee05a38d3b49dc465c9168ff3ad7c70a49f81430e21b7f6b3366`。\n\n- root 执行重启，本验证者只读采集 BEFORE/AFTER，不操作服务、不派发 Task。daemon、AGY Worker、Codex Worker 实际 `/proc/exe` 与发布一致；app-server 是 Codex 0.160.0，其 SHA 与正式 RuntimeIdentity 一致。\n- Codex Worker/app-server PID 与 starttime 均改变；目标代理环境、CODEX_HOME、NO_PROXY 及私密 `.env` hash 保持一致；正式绑定从第1代到第2代，AFTER独立Worker投影、applied回执与ready一致。\n- release-clone/web/dist 的8个工件与安装目录、实际HTTP响应逐字节SHA一致；Go build info 指向发布commit且vcs.modified=false。\n- 首次 version 子命令不存在，原输出保留；改用支持的 help 与 go version -m。BEFORE采集脚本未取独立Worker generation，其同名布尔值不可作为该断言；修正后的AFTER脚本和原脚本分别保存，准确边界见report.json。最初release.txt仍是旧版本，root随后更新，最终副本已保留。\n\n本批只证明安装来源、Web静态工件与环境装配/重启持久性，不证明外网代理已穿透、实际bypass流量、模型效果或产品浏览器交互。私密原件：`/home/sky/.local/state/openagentx/evidence/2026-10-02-codex-workflow/installed-provenance01`；只采目标环境键，不读取auth.json、不保存token或认证头。\n''')
write('capture-assets.py',Path(__file__).read_text())
for d in [raw,repo]:
 p=d/'SHA256SUMS';p.write_text(''.join(sha(x.read_bytes())+'  '+x.name+'\n' for x in sorted(d.iterdir()) if x.is_file() and x.name!='SHA256SUMS'));p.chmod(0o600 if d==raw else 0o644)
print(json.dumps(report,ensure_ascii=False,indent=2))
