import sys,json,pathlib,argparse,subprocess,hashlib,datetime
ROOT=pathlib.Path('/home/sky/work/touzi/OneAxe/OpenAgentX-workflow-worktree');sys.path.insert(0,str(ROOT/'scripts/validation'))
from codex_workflow_e2e import Evidence,require,timestamp
base=pathlib.Path('/home/sky/.local/state/openagentx/validation/2026-10-02-codex-workflow');h=json.loads((base/'installed01/handoff.json').read_text());st=pathlib.Path('/home/sky/.openagentx/workers/codex/codex-domain-e2e');native=json.loads((st/'state.json').read_text());workspace=pathlib.Path(h['workspace'])
a=argparse.Namespace(raw=base/'installed-native01-api',evidence=ROOT/'docs/reports/validation/2026-10-02-codex-workflow/evidence/installed-native01-api',password_file=pathlib.Path('/home/sky/.local/state/openagentx/validation/2026-10-02-agy-workflow/installation/owner-password'),url=h['url'],unit=['openagentx.service',h['unit']],timeout=120,poll_interval=15,adapter_id='codex-app-server')
e=Evidence(a);result={'status':'FAIL','started_at':timestamp()}
try:
 e.save('manifest.json',{'source_commit':h['source_commit'],'agent':h['agent'],'thread_id':h['thread_id'],'command':[sys.executable,*sys.argv]});before=e.provenance('before');e.api('/api/auth/v1/login',{'username':'owner','password':e.password},login=True)
 e.save('native-state.json',native);nd=e.settle(native['task_id']);nr=e.check_run(nd);require('INSTALLED-NATIVE01-DONE' in nd['task'].get('result',''),'native reply mismatch');actual=(workspace/'installed-native01.txt').read_bytes();expected=b'OAX-INSTALLED-NATIVE01\n';e.save('independent-file.json',{'path':str(workspace/'installed-native01.txt'),'contents':actual.decode(),'sha256':hashlib.sha256(actual).hexdigest(),'exact':actual==expected});require(actual==expected,'file mismatch')
 receipt=e.api('/api/control/v1/tasks',{'target_agent_id':h['agent'],'organization_id':'default','dispatch_mode':'direct','intent':'query','runtime_session':{'backend_id':'codex','provider_session_id':h['thread_id']},'content':'Do not call tools. Reply exactly: INSTALLED-NATIVE-CLOSED-NEXT01'});task=receipt['task_id'];e.tasks.append(task);qd=e.settle(task);qr=e.check_run(qd);require(qd['task']['status']=='succeeded' and qd['task']['result'].strip()=='INSTALLED-NATIVE-CLOSED-NEXT01','closed query failed');require((nr['worker_instance_id'],nr['worker_generation'])==(qr['worker_instance_id'],qr['worker_generation']),'worker changed');e.save('query-state.json',json.loads((st/'state.json').read_text()));after=e.provenance('after');require(before==after,'service provenance changed');result.update(status='PASS',native_task=native['task_id'],native_run=nr['run_id'],native_status=nd['task']['status'],query_task=task,query_run=qr['run_id'],worker=qr['worker_instance_id'],generation=qr['worker_generation'])
except Exception as ex:result['error']=str(ex)
finally:
 for label,unit in [('daemon','openagentx.service'),('worker',h['unit'])]:
  p=subprocess.run(['journalctl','--user','-u',unit,'--since',result['started_at'],'--no-pager','-o','short-iso'],capture_output=True,text=True,timeout=20);e.save('journal/'+label+'.json',{'exit':p.returncode,'stdout':p.stdout,'stderr':p.stderr})
 e.save('runtime-log.json',{'contents':(st/'app-server.log').read_text()});result['finished_at']=timestamp();e.save('verdict.json',result);e.finish();print(json.dumps(result,indent=2));sys.exit(0 if result['status']=='PASS' else 1)
