#!/usr/bin/env python3
"""Create an isolated real Codex profile via official CLI/API (R, not installed I).
The persisted environment is generated by join; no ambient proxy is injected.
Owned processes remain available for subsequent PTY/browser verification.
"""
import argparse,datetime,hashlib,json,os,pathlib,secrets,shlex,socket,subprocess,sys,time
import pexpect
sys.path.insert(0,str(pathlib.Path(__file__).resolve().parents[1]/'e2e'))
from agy_live import Live,write
P=pathlib.Path
class Setup(Live):
 def __init__(self,a):
  self.a=a;self.root=a.profile.resolve();self.out=a.evidence.resolve()
  self.root.mkdir(mode=0o700,parents=True,exist_ok=False);self.out.mkdir(parents=True,exist_ok=False)
  self.password=secrets.token_urlsafe(32);(self.root/'password').write_text(self.password)
  self.socket=P('/tmp')/('oax-codex-'+secrets.token_hex(5)+'.sock')
  self.env={k:v for k,v in os.environ.items() if 'proxy' not in k.lower() and not k.startswith(('AGY_','OPENAGENTX_'))}
  self.env.update(OPENAGENTX_HOME=str(self.root/'profile'),OPENAGENTX_SOCKET_PATH=str(self.socket),TERM='xterm-256color')
  import http.cookiejar,urllib.request
  self.jar=http.cookiejar.CookieJar();self.http=urllib.request.build_opener(urllib.request.ProxyHandler({}),urllib.request.HTTPCookieProcessor(self.jar));self.csrf='';self.procs=[];self.request_number=0
  with socket.socket() as s:s.bind(('127.0.0.1',0));self.port=s.getsockname()[1]
  self.url='http://127.0.0.1:'+str(self.port);self.aid='codex-local-e2e'
 def cli(self,label,args):
  child=pexpect.spawn(str(self.a.binary),args,env=self.env,encoding='utf-8',timeout=180,dimensions=(28,100));output=[]
  while True:
   i=child.expect([r'(?i)password[^:\r\n]*:',r'(?i)username:',pexpect.EOF,pexpect.TIMEOUT]);output.append(child.before)
   if i==0:child.sendline(self.password)
   elif i==1:child.sendline('owner')
   elif i==2:break
   else:child.terminate(force=True);raise TimeoutError(label)
  child.close();text=''.join(output).replace(self.password,'[REDACTED]')
  write(self.out/(label+'.json'),{'argv':[str(self.a.binary),*args],'exit':child.exitstatus,'transcript':text})
  if child.exitstatus!=0:raise RuntimeError(label+': '+text[-1500:])
 def run(self):
  w=self.root/'workspace';w.mkdir();(w/'ROLE.md').write_text('You are the Codex workflow verification domain agent. Your role code is OAX-CODEX-ROLE. Only work in the assigned workspace. Execute requested local tests exactly once. Never read credentials or unrelated private files. Follow requested exact output formats.\n')
  self.cli('01-join',['agent','join','--id',self.aid,'--name','Codex 实际链路验收','--workspace',str(w),'--role',str(w/'ROLE.md'),'--model','gpt-6-astra','--prepare'])
  self.cli('02-init',['init'])
  workers=self.root/'profile/workers'
  files=list((self.root/'profile').rglob(self.aid+'.yaml'))
  configs=[p for p in files if '/identities/' not in str(p)];assert len(configs)==1,configs
  config=configs[0];identity=config.parent/'identities'/f'{self.aid}.yaml'
  self.cli('03-apply',['agent','apply','--file',str(identity)])
  self.start('daemon',[str(self.a.binary),'serve','--http-addr','127.0.0.1:'+str(self.port),'--web-dir',str(self.a.web)])
  self.wait(lambda:self.socket.exists())
  self.cli('04-console-login',['console','login'])
  envfile=config.with_suffix('.env')
  for line in envfile.read_text().splitlines():
   if line.strip() and not line.startswith('#'):
    pair=shlex.split(line);assert len(pair)==1;key,value=pair[0].split('=',1);self.env[key]=value
  self.start('worker',[str(self.a.binary),'worker','run','--config',str(config)])
  login=self.api('/api/auth/v1/login',{'username':'owner','password':self.password},auth=True);self.csrf=login['csrf_token']
  self.wait(lambda:any(x['agent_id']==self.aid for x in self.api('/api/observe/v1/overview').get('workers',[])))
  self.cli('05-resume',['agent','resume',self.aid,'--password-file',str(self.root/'password'),'--no-open','--wait','3m'])
  handoff={'root':str(self.root),'url':self.url,'agent':self.aid,'binary':str(self.a.binary),'workspace':str(w),'worker_config':str(config),'socket':str(self.socket),'profile':str(self.root/'profile'),'binary_sha256':hashlib.sha256(self.a.binary.read_bytes()).hexdigest(),'evidence_level':'R isolated profile and formal CLI/API, no installed systemd lifecycle claim','created_at':datetime.datetime.now(datetime.timezone.utc).isoformat()}
  write(self.root/'handoff.json',handoff);write(self.out/'handoff.json',handoff)
  print(json.dumps(handoff),flush=True)
if __name__=='__main__':
 parser=argparse.ArgumentParser();parser.add_argument('--binary',type=P,required=True);parser.add_argument('--web',type=P,required=True);parser.add_argument('--profile',type=P,required=True);parser.add_argument('--evidence',type=P,required=True);a=parser.parse_args();os.umask(0o077)
 s=Setup(a)
 try:s.run()
 except Exception as e:
  write(s.out/'failure.json',{'type':type(e).__name__,'message':str(e).replace(s.password,'[REDACTED]')});raise
