import React,{useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import './styles.css'

const initialAgents=[{id:'quote-service',label:'行情服务',state:'执行中',detail:'Task Q-104 · 运行 08:32',tone:'busy'},{id:'analysis',label:'分析官',state:'待命',detail:'最近心跳 12 秒前',tone:'ready'},{id:'executor',label:'执行官',state:'等待审批',detail:'1 个审批请求',tone:'warn'}]
const initialTasks=[{id:'Q-104',title:'刷新红利股行情',agent:'行情服务',status:'运行中',time:'08:32'},{id:'A-087',title:'复核网格参数',agent:'分析官',status:'待输入',time:'07:58'},{id:'E-021',title:'提交执行计划',agent:'执行官',status:'待审批',time:'07:41'}]

function App(){
 const [tab,setTab]=useState('command');const [agents]=useState(initialAgents);const [tasks]=useState(initialTasks);const [draft,setDraft]=useState('');const [sent,setSent]=useState(false);const [approved,setApproved]=useState(false);const [cancelled,setCancelled]=useState({});const [online,setOnline]=useState(()=>navigator.onLine)
 useEffect(()=>{const handleOnline=()=>setOnline(true);const handleOffline=()=>setOnline(false);window.addEventListener('online',handleOnline);window.addEventListener('offline',handleOffline);return()=>{window.removeEventListener('online',handleOnline);window.removeEventListener('offline',handleOffline)}},[])
 useEffect(()=>{if('serviceWorker' in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{})},[])
 const writeDisabled=!online
 const cancelTask=id=>{if(writeDisabled)return;setCancelled(previous=>({...previous,[id]:true}))}
 return <div className="shell"><header className="top"><div><span className="eyebrow">OPENAGENTX</span><h1>指挥台</h1></div><div className="connection"><i className={online?'':'offline-dot'}/>{online?'在线':'离线'} <button className="avatar" aria-label="账户菜单">主</button></div></header>
 {!online&&<div className="offline-banner" role="status">当前离线，审批、回复、发送和取消已暂停</div>}
 <main>{tab==='command'&&<><section className="hero"><div><p className="eyebrow">组织态势</p><h2>今天的组织运行正常</h2><p className="muted">3 个 Domain Agent · 1 个审批待处理</p></div><button className="primary" onClick={()=>setTab('tasks')}>查看任务 <span>→</span></button></section>
 <section className="section"><div className="section-head"><h3>Agent 状态</h3><button className="text-button" onClick={()=>setTab('org')}>组织视图</button></div><div className="agent-grid">{agents.map(a=><article className="agent" key={a.id}><div className="agent-head"><span className={'status-dot '+a.tone}/><strong>{a.label}</strong><span className="state">{a.state}</span></div><p>{a.detail}</p><button className="link" onClick={()=>setTab('tasks')}>进入工作台 <span>↗</span></button></article>)}</div></section>
 <section className="section"><div className="section-head"><h3>需要你处理</h3><span className="count">2</span></div><div className="attention"><div><b>执行官需要审批</b><p>允许执行「提交执行计划」</p></div><button className="approve" disabled={writeDisabled||approved} onClick={()=>setApproved(true)}>{approved?'已批准':'审批'}</button></div><div className="attention"><div><b>分析官等待输入</b><p>复核网格参数需要下一步指令</p></div><button className="outline" disabled={writeDisabled} onClick={()=>setTab('tasks')}>回复</button></div></section></>}
 {tab==='tasks'&&<section className="page"><div className="page-head"><button className="back" onClick={()=>setTab('command')} aria-label="返回">←</button><div><p className="eyebrow">工作队列</p><h2>任务</h2></div></div><div className="task-list">{tasks.map(t=><article className="task" key={t.id}><div className="task-line"><span className="task-id">{t.id}</span><span className={'pill '+t.status.replace('中','').replace('待','pending')}>{cancelled[t.id]?'已取消':t.status}</span></div><h3>{t.title}</h3><p>{t.agent} · {t.time}</p><div className="task-actions"><button className="link">打开任务 <span>→</span></button>{(t.status==='运行中'||t.status==='待输入')&&!cancelled[t.id]&&<button className="outline" disabled={writeDisabled} onClick={()=>cancelTask(t.id)}>取消</button>}</div></article>)}</div><div className="composer"><label htmlFor="command">向当前指挥链发送指令</label><div><input id="command" value={draft} onChange={e=>setDraft(e.target.value)} placeholder="输入业务指令…" disabled={writeDisabled}/><button className="send" disabled={writeDisabled||!draft.trim()} onClick={()=>{setDraft('');setSent(true)}} aria-label="发送">↑</button></div>{sent&&<small>指令已写入 Agent Mailbox</small>}</div></section>}
 {tab==='org'&&<section className="page"><div className="page-head"><button className="back" onClick={()=>setTab('command')} aria-label="返回">←</button><div><p className="eyebrow">组织</p><h2>责任链</h2></div></div><div className="org-tree"><div className="org-node root"><b>指挥者</b><span>OpenAgentX Owner</span></div>{agents.map(a=><div className="org-node" key={a.id}><b>{a.label}</b><span>{a.state} · {a.id}</span></div>)}</div></section>}</main>
 <nav className="bottom" aria-label="主导航">{[['command','⌂','指挥'],['tasks','▣','任务'],['org','⌘','组织']].map(([key,icon,label])=><button className={tab===key?'active':''} onClick={()=>setTab(key)} key={key}><span>{icon}</span>{label}</button>)}</nav></div>}
createRoot(document.getElementById('root')).render(<App/>)
